### PR TITLE
faster combination if y is integer

### PR DESCRIPTION
**Pull request by kckennylau**

### CODE REVIEW

**Comment by DennisMitchell** [comment]
That uses floating point arithmetic, making it inaccurate for large values of **n**.

**Comment by kckennylau** [comment]
Not really. This formula can guarantee that if left is integer, then all the intermediate values are integers.

**Comment by DennisMitchell** [comment]
Ah, I see what your intentions were. There are two problems though.
1. `/` is _always_ floating point division in Python 3, even if the result is exact.
2. Something is off by one. **10C1** should return **10**, not **1**.

**Comment by kckennylau** [comment]
1. Then condition on left to see if we use / or //
2. Ok I'll fix that (or you'll fix that?)

**Comment by kckennylau** [comment]
I forgot to add one to the second argument of range().

**Comment by kckennylau** [comment]
@DennisMitchell Is it ok now?

**Comment by DennisMitchell** [comment]
Almost. To match the behavior of the previous code, it should return `0` when the right argument is negative. The case of a negative left argument can be considered undefined behavior for now.

**Comment by kckennylau** [comment]
But negative left argument is really defined... They are also useful in binomial expansions.

**Comment by DennisMitchell** [comment]
It is. If you want to implement it correctly, go ahead. I just meant that my code doesn't return anything sensible right now, so there's no reason your code should match its behavior.

**Comment by kckennylau** [comment]
Thanks!

**Comment by DennisMitchell** [comment]
Thank _you_ for the contribution!

I made one more functional change to the code, so that `nCr(2**256, 2**256-1)` is also computed instantly.

**Pull request merged**
