### PR TITLE
Prefix suffix

### PR DESCRIPTION
**Pull request by miles-cg**

### CODE REVIEW

**Comment by GolfingSuccess** [comment]
Huh? Did it have bugs or something?

**Comment by vendethiel** [comment]
It seems they opened a new PR

**Comment by miles-cg** [comment]
I added support for negative nilads. Wasn't sure how to include it in the previous pull so I just made a new one.

**Comment by vendethiel** [comment]
You just need to push. Github picks it up.

**Comment by GolfingSuccess** [comment]
@vendethiel hehe I didn't see that...

**Pull request closed without merging**
