### PR TITLE
Prefix suffix

### PR DESCRIPTION
**Pull request by miles-cg**

### CODE REVIEW

**Comment by GolfingSuccess** [comment]
And...how is this supposed to work?

**Comment by miles-cg** [comment]
It just maps a monad over each prefix. Instead of ``ḣJS€`` (you'd actually would use ``+\`` but pretend sum was any other monad), you can do ``SƤ``. For more info, see the J adverbs ``\`` and ``\.`` since these two quicks are based on those.

**Comment by GolfingSuccess** [comment]
And how do you do in/outfixes?

**Comment by DennisMitchell** [comment]
@GolfingSuccess Please discuss usage in the Jelly room. I don't need an email every time a new reply is added to this conversation.

**Pull request merged**
