### PR TITLE
Added link to Aliases

### PR DESCRIPTION
**Pull request by GolfingSuccess**
Aliases are a crucial golfing feature of Jelly, one can't miss them.

### CODE REVIEW

**Comment by dylannrees** [comment]
Shouldn't we just put the shorter aliases in the respective atom/syntax/quick pages?

**Comment by DennisMitchell** [comment]
Yeah, I don't think the documentation should make any distinction between atoms/quicks and their aliases.

**Comment by GolfingSuccess** [comment]
@dylannrees @DennisMitchell For the record, the reason I've put the Aliases in a separate page is because I believe they can be more than just single atoms/quicks, for example, what if `ẎS$` (with the appropriate chaining done in Python of course) becomes an alias? By the way, if you ask me, I would rather say that Aliases shouldn't really be a different term from Atoms and Quicks, so the other possible thing to do is to just list them in the same way as those and forget about "aliases".

**Comment by GolfingSuccess** [comment]
The Aliases page wasn't preferred, why keep this open? :wink:

**Pull request closed without merging**
